version: '3.7'

services:
  frontend:
    image: frontend
    ports:
      - 4200
    depends_on:
      - backend
  backend:
    image: backend
    ports:
      - 4000
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest